### ISSUE TITLE
grammar error

### ISSUE THREAD

**Issue by kkimb003** [fundamelon/terminal-game-tutorial#17]
it says You should now a makefile target for game.cpp" in part 2.1 what did you mean instead?

**Comment by fundamelon** [comment]
Should be "write a makefile target"

Closed, fixed in c0fda27b1280132e0c35bec61bfe6f6a46a72e71

**Comment by kkimb003** [comment]
part 2 doesnt specifically say to remove the hello world code

**Comment by fundamelon** [comment]
It does here: https://github.com/fundamelon/terminal-game-tutorial/edit/final/part2/README.md#L265
